name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: 'app'
    steps:
    - uses: actions/checkout@v4
    - name: ls
      run: ls
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version-file: 'app/.nvmrc'
        cache: 'npm'
        # cache-dependency-path: './app/package-lock.json'

    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm test
